{{- if eq .Values.kubetail.authMode "cluster" }}
{{- $crb := index .Values "kubetail" "clusterRoleBinding" -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $crb.name | default (include "kubetail.fullname" .) }}
  labels:
    {{- include "kubetail.labels" . | nindent 4 }}
    {{- with $crb.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kubetail.annotations" . | nindent 4 }}
    {{- with $crb.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubetail.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubetail.serviceAccountName" . }}
  namespace: {{ include "kubetail.namespace" . }}
{{- end }}
