{{- if eq .Values.kubetail.authMode "cluster" }}
{{- $sa := index .Values "kubetail" "serviceAccount" -}}
kind: ServiceAccount
apiVersion: v1
automountServiceAccountToken: {{ $sa.automountServiceAccountToken }}
metadata:
  name: {{ $sa.name | default (include "kubetail.fullname" .) }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.labels" . | nindent 4 }}
    {{- with $sa.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kubetail.annotations" . | nindent 4 }}
    {{- with $sa.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
