apiVersion: v2
name: kubetail
description: Kubetail is a private, real-time log viewer for Kubernetes clusters
keywords:
- kubetail
- kubernetes
- logging
- private
- realtime
type: application
version: 0.1.7
appVersion: "0.1.1"
home: https://github.com/kubetail-org/kubetail
maintainers:
- email: andres@kubetail.com
  name: Andres Morey
  url: https://github.com/kubetail-org
icon: https://github.com/kubetail-org/kubetail/raw/main/assets/kubetail-circle-icon.svg
