{{- $ds := index .Values "kubetail" "agent" "daemonSet" -}}
{{- $podTmpl := index .Values "kubetail" "agent" "podTemplate" }}
{{- $container := index .Values "kubetail" "agent" "container" -}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "kubetail.agent.daemonSetName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.agent.labels" (list $ $ds.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $ds.annotations) | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubetail.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubetail.agent.labels" (list $ $podTmpl.labels) | indent 8 }}
      annotations:
        {{- include "kubetail.annotations" (list $ $podTmpl.annotations) | indent 8 }}
        checksum/config: {{ include "kubetail.agent.config" . | sha256sum | quote }}
    spec:
      automountServiceAccountToken: true
      {{- if eq .Values.kubetail.authMode "cluster" }}
      serviceAccountName: {{ include "kubetail.agent.serviceAccountName" . }}
      {{- end }}
      securityContext:
        fsGroup: 0
      containers:
      - name: {{ $container.name }}
        image: {{ include "kubetail.agent.image" . }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          privileged: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        imagePullPolicy: {{ .Values.kubetail.agent.image.pullPolicy }}
        env:
        {{- with $container.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        {{- with $container.envFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        args:
        - --config=/etc/kubetail/config.yaml
        ports:
        - name: kubetail-agent
          protocol: TCP
          containerPort: {{ .Values.kubetail.agent.runtimeConfig.port }}
        livenessProbe:
          grpc:
            port: {{ .Values.kubetail.agent.runtimeConfig.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 3
          failureThreshold: 3
        readinessProbe:
          grpc:
            port: {{ .Values.kubetail.agent.runtimeConfig.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 3
          failureThreshold: 3
        resources:
          {{- with $container.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/kubetail
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      {{- with $podTmpl.containers  }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "kubetail.agent.configMapName" . }}
      - name: varlog
        hostPath:
          path: /var/log
      nodeSelector:
        {{- with $podTmpl.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      affinity:
        {{- with $podTmpl.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      tolerations:
      {{- with $podTmpl.tolerations }}
      {{- toYaml . | nindent 6 }}
      {{- end}}
